name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish
        run: ./gradlew publish
        env:
           RELEASE_VERSION: ${{ github.event.inputs.version }}
           OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
           OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
           ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
           ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}


  macos:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Publish Snapshot
        if: github.ref == 'refs/heads/master'
        run: ./gradlew publishMacosX64PublicationToMavenRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}


  windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
      - name: Publish Snapshot
        if: github.ref == 'refs/heads/master'
        run: ./gradlew publishMingwX64PublicationToMavenRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SIGNING_PASSWORD }}
